CREATE USER DW_RM IDENTIFIED BY 1234;

CREATE USER DW_PB IDENTIFIED BY 1234;

# RIA_ITEM_ANAL_FCT 테이블 생성 로직입니다.
CREATE TABLE DW_RM.RIA_ITEM_ANAL_FCT
(
    SLITM_CD                    VARCHAR2(12) NOT NULL,
    SLITM_NM                    VARCHAR2(100),
    ITEM_REG_YR                 VARCHAR2(4),
    PLU_CD                      VARCHAR2(18),
    BRND_CD                     VARCHAR2(6),
    BRND_NM                     VARCHAR2(200),
    EXPS_BRND_NM                VARCHAR2(200),
    ITEM_L_CSF_CD               VARCHAR2(8),
    ITEM_M_CSF_CD               VARCHAR2(8),
    ITEM_S_CSF_CD               VARCHAR2(8),
    ITEM_D_CSF_CD               VARCHAR2(8),
    ITEM_L_CSF_NM               VARCHAR2(100),
    ITEM_M_CSF_NM               VARCHAR2(100),
    ITEM_S_CSF_NM               VARCHAR2(100),
    ITEM_D_CSF_NM               VARCHAR2(100),
    ITEM_D_CSF_USE_YN           VARCHAR2(1),
    ITEM_SELL_GBCD              VARCHAR2(2),
    ITEM_SELL_GB_NM             VARCHAR2(50),
    VEN_CD                      VARCHAR2(6),
    VEN_NM                      VARCHAR2(100),
    VEN_REG_DT                  VARCHAR2(8),
    VTLT_STAT_GBCD              VARCHAR2(1),
    VTLT_STAT_GB_NM             VARCHAR2(100),
    FRST_MD_CONT_ASGNR_ID       VARCHAR2(50),
    FRST_MD_CONT_ASGNR_NM       VARCHAR2(50),
    MKCO_CD                     VARCHAR2(6),
    MKCO_NM                     VARCHAR2(100),
    OCTY_NM                     VARCHAR2(100),
    OCTY_CNRY_GBCD              VARCHAR2(4),
    PRMR_ORG_CNRY_GBCD          VARCHAR2(4),
    PRMR_ORG_CNRY_NM            VARCHAR2(100),
    PRMR_ORG_NM                 VARCHAR2(100),
    WINT_INSM_MTHS              NUMBER,
    WINT_INSM_SETUP_APLY_YN     VARCHAR2(1),
    ITNT_DISP_YN                VARCHAR2(1),
    PRCH_MTHD_GBCD              VARCHAR2(2),
    PRCH_MTHD_GB_NM             VARCHAR2(100),
    PREV_PAY_TRGT_YN            VARCHAR2(1),
    CMIS_GBCD                   VARCHAR2(1),
    CMIS_GB_NM                  VARCHAR2(50),
    ITEM_GBCD                   VARCHAR2(2),
    ITEM_GB_NM                  VARCHAR2(50),
    INTG_ITEM_STLM_YN           VARCHAR2(1),
    ITEM_QA_RST_GBCD            VARCHAR2(2),
    ITEM_QA_RST_GB_NM           VARCHAR2(50),
    PRCH_PRC                    NUMBER,
    SELL_PRC                    NUMBER,
    VEN2_CD                     VARCHAR2(6),
    VEN2_NM                     VARCHAR2(100),
    DPTS_PCH_CD                 VARCHAR2(11),
    DPTS_PCH_NM                 VARCHAR2(100),
    VEN_ITEM_CD                 VARCHAR2(20),
    ADLT_ITEM_YN                VARCHAR2(1),
    LRPY_YN                     VARCHAR2(1),
    INTG_ITEM_GBCD              VARCHAR2(2),
    INTG_ITEM_GB_NM             VARCHAR2(100),
    SLITM_APRVL_GBCD            VARCHAR2(1),
    SLITM_APRVL_GB_NM           VARCHAR2(100),
    HMALL_DLBR_STAT_GBCD        VARCHAR2(2),
    HMALL_DLBR_STAT_GB_NM       VARCHAR2(100),
    HMALL_ITEM_SRCH_EXCLD_YN    VARCHAR2(1),
    PACK_OPEN_RTP_NDMT_YN       VARCHAR2(1),
    DLV_HOPE_DT_DSNT_YN         VARCHAR2(1),
    CUST_DLVC_WDMT_GB_NM        VARCHAR2(50),
    EXCH_DSRV_COST              NUMBER,
    EXCH_WDMT_GB_NM             VARCHAR2(50),
    RTP_DSRV_COST               NUMBER,
    RTP_WDMT_GB_NM              VARCHAR2(50),
    ITEM_TAXN_YN                VARCHAR2(1),
    HSCD                        VARCHAR2(10),
    ENG_ITEM_NM                 VARCHAR2(100),
    ITEM_WGT                    NUMBER,
    ITEM_WDTH_LEN               NUMBER,
    ITEM_HGHT_LEN               NUMBER,
    ITEM_HGH_LEN                NUMBER,
    INSL_ITEM_YN                VARCHAR2(1),
    ODTM_DEAL_YN                VARCHAR2(1),
    TC_DC_EXPS_YN               VARCHAR2(1),
    SCM_HLDY_EXCLD_YN           VARCHAR2(1),
    AIR_DLV_YN                  VARCHAR2(1),
    CMIS_HMALL_EXPS_YN          VARCHAR2(1),
    THDY_OSHP_GD_YN             VARCHAR2(1),
    MEAT_HIS_YN                 VARCHAR2(1),
    LWST_BUY_QTY                NUMBER,
    PREM_DLV_YN                 VARCHAR2(1),
    DSNT_TIME_WTDW_YN           VARCHAR2(1),
    DPTS_VEN_OP_CD              VARCHAR2(2),
    DEAL_ITEM_YN                VARCHAR2(1),
    TRNDH_EXCL_TAG_EXPS_YN      VARCHAR2(1),
    ONAIR_POSS_YN               VARCHAR2(1),
    USER_GB_NM                  VARCHAR2(100),
    SELL_HOPE_STAT_GBCD         VARCHAR2(1),
    SELL_HOPE_STAT_GB_NM        VARCHAR2(100),
    PRC_COMP_COPN_DC_YN         VARCHAR2(1),
    ITEM_TAXN_GBCD              VARCHAR2(3),
    ITEM_TAXN_GB_NM             VARCHAR2(50),
    MD_CD                       VARCHAR2(4),
    SRCN_MD_CD                  VARCHAR2(4),
    DLV_FORM_JDGM_YN            VARCHAR2(1),
    MRGN_JDGM_CMPT_YN           VARCHAR2(1),
    REIT_YN                     VARCHAR2(1),
    CHILD_ITEM_YN               VARCHAR2(1),
    SAFE_MNG_TRGT_YN            VARCHAR2(1),
    PARL_IMPR_YN                VARCHAR2(1),
    ALLI_CRD_DC_YN              VARCHAR2(1),
    DMND_DC_EXCLD_YN            VARCHAR2(1),
    ORD_MAKE_YN                 VARCHAR2(1),
    STPIC_POSS_YN               VARCHAR2(1),
    ST11_ALLI_ITEM_CD           VARCHAR2(20),
    AUCT_ALLI_ITEM_CD           VARCHAR2(20),
    CPG_ALLI_ITEM_CD            VARCHAR2(20),
    EZW_ALLI_ITEM_CD            VARCHAR2(20),
    GMKT_GLOB_ALLI_ITEM_CD      VARCHAR2(20),
    GMKT_ALLI_ITEM_CD           VARCHAR2(20),
    KB_ALLI_ITEM_CD             VARCHAR2(20),
    NACF_ALLI_ITEM_CD           VARCHAR2(20),
    NAVER_ALLI_ITEM_CD          VARCHAR2(20),
    WLML_ALLI_ITEM_CD           VARCHAR2(20),
    WMPW_ALLI_ITEM_CD           VARCHAR2(20),
    WMP_ALLI_ITEM_CD            VARCHAR2(20),
    CTPF_AMT                    NUMBER,
    DLV_COST                    NUMBER,
    PHDS_LACO                   NUMBER,
    PACK_CHRG_COST              NUMBER,
    CALL_LACO                   NUMBER,
    NCHG_CALL_COST              NUMBER,
    SVMT                        NUMBER,
    GIFT_COST                   NUMBER,
    PRMP_COST                   NUMBER,
    CRD_FRCS_CMIS               NUMBER(15),
    WINT_INSM_CMIS              NUMBER(15),
    CMS_CMIS                    NUMBER(15),
    GC_CMIS                     NUMBER(15),
    GRNT_SVMT                   NUMBER,
    JWL_JGMT_COST               NUMBER,
    ARS_OWCO_CHRG_AMT           NUMBER,
    CTPF_RATE                   NUMBER(8,3),
    DPTS_OP_CD                  VARCHAR2(2),
    PRCH_VAT                    NUMBER(13),
    SELL_VAT                    NUMBER(13),
    MRGN_AMT                    NUMBER,
    MRGN_RATE                   NUMBER(22,2),
    DAWN_DLV_YN                 VARCHAR2(1),
    CVST_DLV_YN                 VARCHAR2(1),
    RLF_DLV_YN                  VARCHAR2(1),
    QA_NO                       VARCHAR2(13),
    QA_CLNT_ID                  VARCHAR2(20),
    PQA_ASGNR_ID                VARCHAR2(50),
    QA_RST_GBCD                 VARCHAR2(2),
    QA_ASK_DTM                  DATE,
    PQA_ACPT_DTM                DATE,
    PQA_ASGNR_CMPT_DTM          DATE,
    SAFE_CRTI_GBCD              VARCHAR2(2),
    SAFE_CERT_CLAS_GBCD         VARCHAR2(2),
    LAST_CHG_DTM                DATE,
    RGST_ID                     VARCHAR2(50) NOT NULL,
    ETL_DTM                     DATE NOT NULL
)
TABLESPACE TS_DW_RM_01_DAT
STORAGE
(
    INITIAL 64K
    NEXT 1M
)
NOLOGGING
NOCOMPRESS;

ALTER TABLE DW_RM.RIA_ITEM_ANAL_FCT
ADD CONSTRAINT PK_RIA_ITEM_ANAL_FCT PRIMARY KEY (SLITM_CD);

GRANT SELECT ON DW_RM.RIA_ITEM_ANAL_FCT TO DW_IMSI;
GRANT SELECT ON DW_RM.RIA_ITEM_ANAL_FCT TO DW_PB WITH GRANT OPTION;
GRANT SELECT ON DW_RM.RIA_ITEM_ANAL_FCT TO H2O_READING;

COMMENT ON TABLE DW_RM.RIA_ITEM_ANAL_FCT IS '상품분석팩트';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.SLITM_CD IS '판매상품코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.SLITM_NM IS '판매상품명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_REG_YR IS '상품등록년도';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.PLU_CD IS '단품코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.BRND_CD IS '브랜드코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.BRND_NM IS '브랜드명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.EXPS_BRND_NM IS '노출브랜드명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_L_CSF_CD IS '상품대분류코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_M_CSF_CD IS '상품중분류코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_S_CSF_CD IS '상품소분류코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_D_CSF_CD IS '상품세분류코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_L_CSF_NM IS '상품대분류명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_M_CSF_NM IS '상품중분류명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_S_CSF_NM IS '상품소분류명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_D_CSF_NM IS '상품세분류명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_D_CSF_USE_YN IS '상품세분류사용여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_SELL_GBCD IS '상품판매구분코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_SELL_GB_NM IS '상품판매구분명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.VEN_CD IS '협력사코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.VEN_NM IS '협력사명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.VEN_REG_DT IS '협력사등록일자';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.VTLT_STAT_GBCD IS '활성상태구분코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.VTLT_STAT_GB_NM IS '활성상태구분명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.FRST_MD_CONT_ASGNR_ID IS '최초MD계약담당자ID';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.FRST_MD_CONT_ASGNR_NM IS '최초MD계약담당자명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.MKCO_CD IS '제조사코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.MKCO_NM IS '제조사명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.OCTY_NM IS '원산지명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.OCTY_CNRY_GBCD IS '원산지국가구분코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.PRMR_ORG_CNRY_GBCD IS '주요원료국가구분코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.PRMR_ORG_CNRY_NM IS '주요원료국가명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.PRMR_ORG_NM IS '주요원료명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.WINT_INSM_MTHS IS '무이자할부개월수';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.WINT_INSM_SETUP_APLY_YN IS '무이자할부설정적용여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITNT_DISP_YN IS '인터넷전시여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.PRCH_MTHD_GBCD IS '매입방법구분코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.PRCH_MTHD_GB_NM IS '매입방법구분명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.PREV_PAY_TRGT_YN IS '사전지불대상여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.CMIS_GBCD IS '수수료구분코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.CMIS_GB_NM IS '수수료구분명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_GBCD IS '상품구분코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_GB_NM IS '상품구분명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.INTG_ITEM_STLM_YN IS '무형상품결제여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_QA_RST_GBCD IS '상품QA결과구분코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_QA_RST_GB_NM IS '상품QA결과구분명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.PRCH_PRC IS '매입가격';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.SELL_PRC IS '판매가격';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.VEN2_CD IS '2차협력사코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.VEN2_NM IS '2차협력사명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.DPTS_PCH_CD IS '백화점펀칭코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.DPTS_PCH_NM IS '백화점펀칭명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.VEN_ITEM_CD IS '협력사상품코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ADLT_ITEM_YN IS '성인상품여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.LRPY_YN IS '후환불여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.INTG_ITEM_GBCD IS '무형상품구분코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.INTG_ITEM_GB_NM IS '무형상품구분명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.SLITM_APRVL_GBCD IS '판매상품승인구분코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.SLITM_APRVL_GB_NM IS '판매상품승인구분명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.HMALL_DLBR_STAT_GBCD IS 'HMALL심의상태구분코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.HMALL_DLBR_STAT_GB_NM IS 'HMALL심의상태구분명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.HMALL_ITEM_SRCH_EXCLD_YN IS 'HMALL상품검색제외여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.PACK_OPEN_RTP_NDMT_YN IS '포장오픈반품불가여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.DLV_HOPE_DT_DSNT_YN IS '배송희망일자지정여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.CUST_DLVC_WDMT_GB_NM IS '고객배송비회수방법구분명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.EXCH_DSRV_COST IS '교환택배비용';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.EXCH_WDMT_GB_NM IS '교환회수방법구분명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.RTP_DSRV_COST IS '반품택배비용';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.RTP_WDMT_GB_NM IS '반품회수방법구분명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_TAXN_YN IS '상품과세여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.HSCD IS 'HS코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ENG_ITEM_NM IS '영문상품명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_WGT IS '상품중량';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_WDTH_LEN IS '상품가로길이';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_HGHT_LEN IS '상품세로길이';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_HGH_LEN IS '상품높이길이';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.INSL_ITEM_YN IS '설치상품여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ODTM_DEAL_YN IS '상시딜여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.TC_DC_EXPS_YN IS 'TC할인노출여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.SCM_HLDY_EXCLD_YN IS 'SCM휴일제외여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.AIR_DLV_YN IS '항공배송여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.CMIS_HMALL_EXPS_YN IS '수수료HMALL노출여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.THDY_OSHP_GD_YN IS '당일출고안내여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.MEAT_HIS_YN IS '육류이력여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.LWST_BUY_QTY IS '최저구매수량';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.PREM_DLV_YN IS '프리미엄배송여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.DSNT_TIME_WTDW_YN IS '지정시간회수여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.DPTS_VEN_OP_CD IS '백화점협력사OP코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.DEAL_ITEM_YN IS '딜상품여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.TRNDH_EXCL_TAG_EXPS_YN IS '트렌드H전용태그노출여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ONAIR_POSS_YN IS '생방송진행가능여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.USER_GB_NM IS '사용자구분명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.SELL_HOPE_STAT_GBCD IS '판매희망상태구분코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.SELL_HOPE_STAT_GB_NM IS '판매희망상태구분명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.PRC_COMP_COPN_DC_YN IS '가격비교쿠폰할인여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_TAXN_GBCD IS '상품과세구분코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ITEM_TAXN_GB_NM IS '상품과세구분명';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.MD_CD IS 'MD코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.SRCN_MD_CD IS '소싱MD코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.DLV_FORM_JDGM_YN IS '배송형태심사여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.MRGN_JDGM_CMPT_YN IS '마진심사완료여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.REIT_YN IS '리퍼브상품여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.CHILD_ITEM_YN IS '자녀상품여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.SAFE_MNG_TRGT_YN IS '안전관리대상여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.PARL_IMPR_YN IS '병행수입여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ALLI_CRD_DC_YN IS '제휴카드할인여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.DMND_DC_EXCLD_YN IS '청구할인제외여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ORD_MAKE_YN IS '주문제작여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.STPIC_POSS_YN IS '스토어픽가능여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ST11_ALLI_ITEM_CD IS '11번가제휴상품코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.AUCT_ALLI_ITEM_CD IS '옥션제휴상품코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.CPG_ALLI_ITEM_CD IS '쿠팡제휴상품코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.EZW_ALLI_ITEM_CD IS '이지웰제휴상품코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.GMKT_GLOB_ALLI_ITEM_CD IS 'G마켓글로벌제휴상품코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.GMKT_ALLI_ITEM_CD IS 'G마켓제휴상품코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.KB_ALLI_ITEM_CD IS 'KB제휴상품코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.NACF_ALLI_ITEM_CD IS '농업협동조합제휴상품코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.NAVER_ALLI_ITEM_CD IS '네이버제휴상품코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.WLML_ALLI_ITEM_CD IS '웰몰제휴상품코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.WMPW_ALLI_ITEM_CD IS '위메프W제휴상품코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.WMP_ALLI_ITEM_CD IS '위메프제휴상품코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.CTPF_AMT IS '공헌이익금액';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.DLV_COST IS '배송비용';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.PHDS_LACO IS '물류인건비';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.PACK_CHRG_COST IS '포장부담비용';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.CALL_LACO IS '콜인건비';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.NCHG_CALL_COST IS '무료콜비용';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.SVMT IS '적립금';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.GIFT_COST IS '사은품비용';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.PRMP_COST IS '경품비용';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.CRD_FRCS_CMIS IS '카드가맹점수수료';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.WINT_INSM_CMIS IS '무이자할부수수료';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.CMS_CMIS IS 'CMS수수료';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.GC_CMIS IS '상품권수수료';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.GRNT_SVMT IS '부여적립금';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.JWL_JGMT_COST IS '보석감정비용';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ARS_OWCO_CHRG_AMT IS 'ARS자사부담금액';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.CTPF_RATE IS '공헌이익비율';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.DPTS_OP_CD IS '백화점OP코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.PRCH_VAT IS '매입부가세';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.SELL_VAT IS '판매부가세';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.MRGN_AMT IS '마진금액';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.MRGN_RATE IS '마진비율';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.DAWN_DLV_YN IS '새벽배송여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.CVST_DLV_YN IS '편의점배송여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.RLF_DLV_YN IS '안심배송여부';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.QA_NO IS 'QA번호';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.QA_CLNT_ID IS 'QA의뢰자ID';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.PQA_ASGNR_ID IS '사전QA담당자ID';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.QA_RST_GBCD IS 'QA결과구분코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.QA_ASK_DTM IS 'QA의뢰일시';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.PQA_ACPT_DTM IS '사전QA접수일시';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.PQA_ASGNR_CMPT_DTM IS '사전QA담당자완료일시';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.SAFE_CRTI_GBCD IS '안전인증기관구분코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.SAFE_CERT_CLAS_GBCD IS '안전인증항목구분코드';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.LAST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.RGST_ID IS '등록자ID';
COMMENT ON COLUMN DW_RM.RIA_ITEM_ANAL_FCT.ETL_DTM IS 'ETL일시';