# POD_ORD_ANAL_DLU_FCT_01 테이블 생성 로직입니다.
CREATE TABLE DW_PB.POD_ORD_ANAL_DLU_FCT_01
(
    BSIC_DT                     DATE NOT NULL,
    ORD_NO                      VARCHAR2(14) NOT NULL,
    ORD_PTC_SEQ                 NUMBER(9) NOT NULL,
    ORD_DT                      DATE,
    ORD_DTM                     DATE,
    ORD_SRC_GBCD                VARCHAR2(1),
    ACPT_DT                     DATE,
    ACPT_DTM                    DATE,
    CNCL_DT                     DATE,
    RTP_ACPT_DT                 DATE,
    RTP_CMPT_DT                 DATE,
    REPY_DT                     DATE,
    DSTF_CNSL_DT                DATE,
    OSHP_DT                     DATE,
    CUST_NO                     VARCHAR2(12),
    DSTN_SEQ                    VARCHAR2(10),
    SELL_MDA_GBCD               VARCHAR2(2),
    SELL_MDA_GB_NM              VARCHAR2(100),
    SELL_MDA_NO                 VARCHAR2(6),
    SELL_MDA_NM                 VARCHAR2(100),
    SELL_MDA_L_CSF_CD           VARCHAR2(8),
    SELL_MDA_L_CSF_NM           VARCHAR2(100),
    SELL_MDA_M_CSF_CD           VARCHAR2(8),
    SELL_MDA_M_CSF_NM           VARCHAR2(100),
    SELL_MDA_S_CSF_CD           VARCHAR2(8),
    SELL_MDA_S_CSF_NM           VARCHAR2(100),
    SELL_MDA_L_CSF_CD_BIZ_STRG  VARCHAR2(100),
    SLITM_CD                    VARCHAR2(12),
    SLITM_NM                    VARCHAR2(100),
    ITEM_GBCD                   VARCHAR2(2),
    BRND_CD                     VARCHAR2(6),
    BRND_NM                     VARCHAR2(200),
    PRCH_MTHD_GBCD              VARCHAR2(2),
    PRCH_MTHD_GB_NM             VARCHAR2(100),
    FAMT_FXRT_GBCD              VARCHAR2(1),
    FAMT_FXRT_GB_NM             VARCHAR2(100),
    PRM_ITEM_CSF                VARCHAR2(100),
    SCDR_ITEM_CSF               VARCHAR2(100),
    INTG_ITEM_STLM_YN           VARCHAR2(1),
    SET_ITEM_YN                 VARCHAR2(1),
    SET_ORD_PTC_SEQ             NUMBER(9),
    SET_SLITM_CD                VARCHAR2(12),
    UITM_CD                     VARCHAR2(5),
    ITEM_PRC_APLY_DT            DATE,
    MD_CD                       VARCHAR2(4),
    MD_NM                       VARCHAR2(100),
    DVSN_CD                     VARCHAR2(6),
    DVSN_NM                     VARCHAR2(100),
    TEAM_CD                     VARCHAR2(6),
    TEAM_NM                     VARCHAR2(100),
    PART_CD                     VARCHAR2(10),
    PART_NM                     VARCHAR2(100),
    SRCN_MD_CD                  VARCHAR2(4),
    SRCN_MD_NM                  VARCHAR2(100),
    BROD_MD_CD                  VARCHAR2(4),
    HMALL_MD_CD                 VARCHAR2(4),
    SECT_ID                     NUMBER,
    INFW_CH_CD                  VARCHAR2(3),
    INFW_CH_NM                  VARCHAR2(100),
    INFW_CH_L_CSF_NM            VARCHAR2(100),
    INFW_CH_M_CSF_NM            VARCHAR2(100),
    TC_CD                       VARCHAR2(10),
    VEN_CD                      VARCHAR2(6),
    VEN_NM                      VARCHAR2(100),
    MDA_CROS_ARLT_ANAL_GBCD     VARCHAR2(2),
    MDA_CROS_ARLT_ANAL_GB_NM    VARCHAR2(100),
    ALSW_NO                     NUMBER,
    BFMT_NO                     VARCHAR2(12),
    PGM_CD                      VARCHAR2(6),
    PGM_NM                      VARCHAR2(100),
    WEB_INF_EXPS_GBCD           VARCHAR2(2),
    WEB_INF_EXPS_GB_NM          VARCHAR2(100),
    ORD_TYPE_GBCD               VARCHAR2(2),
    DSTF_CNSL_CSF_CD            VARCHAR2(6),
    LAST_ORD_STAT_GBCD          VARCHAR2(2),
    LAST_ORD_STAT_GB_NM         VARCHAR2(100),
    CNCL_CNSL_CSF_CD            VARCHAR2(6),
    ORD_ITEM_GBCD               VARCHAR2(2),
    BEF_ACPT_ORD_PTC_SEQ        NUMBER(9),
    FRST_ACPT_ORD_PTC_SEQ       NUMBER(9),
    CMPS_ORPD_ORD_PTC_SEQ       NUMBER(9),
    EXCH_BNDL_ORD_PTC_SEQ       NUMBER(9),
    ACPT_CH_GBCD                VARCHAR2(2),
    ACPT_CH_GB_NM               VARCHAR2(100),
    FRST_REG_PRCH_MDA_GBCD      VARCHAR2(2),
    FRST_REG_PRCH_MDA_GB_NM     VARCHAR2(50),
    ITEM_MDA_GBCD               VARCHAR2(2),
    ITEM_MDA_GB_NM              VARCHAR2(100),
    BROD_MDA_GBCD               VARCHAR2(2),
    BROD_MDA_GB_NM              VARCHAR2(100),
    MNG_WH_NO                   VARCHAR2(3),
    DLV_MAGN_GBCD               VARCHAR2(2),
    DLVCO_CD                    VARCHAR2(2),
    LRPY_YN                     VARCHAR2(1),
    GIFT_PRMO_NO                VARCHAR2(13),
    SELL_UPRC                   NUMBER(10),
    ORD_QTY                     NUMBER,
    CNCL_QTY                    NUMBER,
    RTP_QTY                     NUMBER,
    RTP_CNCL_QTY                NUMBER,
    EXCH_QTY                    NUMBER,
    ORD_ETC_QTY                 NUMBER,
    ACPT_QTY                    NUMBER,
    RMND_QTY                    NUMBER,
    RORD_QTY                    NUMBER,
    GIFT_ORD_QTY                NUMBER,
    GIFT_RORD_QTY               NUMBER,
    GIFT_CNCL_QTY               NUMBER,
    GIFT_RTP_QTY                NUMBER,
    GIFT_RTP_CNCL_QTY           NUMBER,
    DC_RATE                     NUMBER(22,2),
    VAT_RATE                    NUMBER(22,2),
    TAXN_JDGM_YN                VARCHAR2(1),
    ORD_ETC_AMT                 NUMBER,
    EXP_CTPF_AMT                NUMBER,
    PRFT_AMT                    NUMBER,
    DC_AMT                      NUMBER(10),
    MRGN_AMT                    NUMBER,
    TRD_AMT                     NUMBER,
    GMV_AMT                     NUMBER,
    ORD_AMT_VAT                 NUMBER,
    CNCL_AMT_VAT                NUMBER,
    RTP_AMT_VAT                 NUMBER,
    RTP_CNCL_AMT_VAT            NUMBER,
    PRCH_PRC                    NUMBER,
    PRCH_VAT                    NUMBER(13),
    SELL_PRC                    NUMBER,
    SELL_VAT                    NUMBER(13),
    MRGN_RATE                   NUMBER(22,2),
    EXP_SWRT_APLY_DT            DATE,
    EXP_SWRT                    NUMBER(5,2),
    REAL_SWRT                   NUMBER(5,2),
    EXP_CTPF_RATE               NUMBER(8,3),
    DLV_FORM_GBCD               VARCHAR2(2),
    VEN_CHRG_AMT                NUMBER,
    ONLN_EXCL_ITEM_SWTC_YN      VARCHAR2(1),
    SELL_PNTM_GBCD              VARCHAR2(2),
    LBRD_L_CSF_NM               VARCHAR2(100),
    LBRD_M_CSF_NM               VARCHAR2(100),
    FXTM_DLV_YN                 VARCHAR2(1),
    FXTM_DLV_REQ_NO             VARCHAR2(13),
    STLM_PRM_PAY_WAY_GBCD       VARCHAR2(2),
    STLM_PRM_PAY_WAY_GB_NM      VARCHAR2(100),
    STLM_PRM_FNC_ISTN_CD        VARCHAR2(3),
    STLM_PRM_CRDC_NM            VARCHAR2(100),
    STLM_PRM_INSM_MTHS          NUMBER,
    STLM_PRM_WINT_YN            VARCHAR2(1),
    STLM_PRM_WINT_CMIS          NUMBER(15),
    STLM_PRM_PAY_WAY_ADT_RATE   NUMBER,
    STLM_PRM_CRDC_CMIS_RATE     NUMBER,
    STLM_PRM_INSM_CMIS_RATE     NUMBER,
    STLM_PRM_CRDC_CMIS          NUMBER(15),
    STLM_PRM_INSM_CMIS          NUMBER(15),
    STLM_PRM_STLM_WAY_C_AMT     NUMBER,
    STLM_PRM_SUM_CMIS           NUMBER(15),
    STLM_PRM_CPAY_PATH_GBCD     VARCHAR2(3),
    STLM_PRM_VAN_GBCD           VARCHAR2(2),
    STLM_PRM_REPY_POSS_AMT      NUMBER,
    STLM_PRM_HDCRD_CLCC_YN      VARCHAR2(1),
    STLM_STAT_GBCD              VARCHAR2(2),
    STLM_STAT_GB_NM             VARCHAR2(100),
    WINT_CMIS                   NUMBER(15),
    CRDC_CMIS                   NUMBER(15),
    INSM_CMIS                   NUMBER(15),
    SUM_CMIS                    NUMBER(15),
    REPY_POSS_AMT               NUMBER,
    STLM_AMT                    NUMBER,
    CMPX_STLM_YN                VARCHAR2(1),
    STLM_SCDR_PAY_WAY_GBCD      VARCHAR2(2),
    STLM_SCDR_PAY_WAY_GB_NM     VARCHAR2(100),
    STLM_SCDR_FNC_ISTN_CD       VARCHAR2(3),
    STLM_SCDR_CRDC_NM           VARCHAR2(100),
    STLM_SCDR_INSM_MTHS         NUMBER,
    STLM_SCDR_WINT_YN           VARCHAR2(1),
    STLM_SCDR_WINT_CMIS         NUMBER(15),
    STLM_SCDR_PAY_WAY_ADT_RATE  NUMBER,
    STLM_SCDR_CRDC_CMIS_RATE    NUMBER,
    STLM_SCDR_INSM_CMIS_RATE    NUMBER,
    STLM_SCDR_CRDC_CMIS         NUMBER(15),
    STLM_SCDR_INSM_CMIS         NUMBER(15),
    STLM_SCDR_STLM_WAY_C_AMT    NUMBER,
    STLM_SCDR_SUM_CMIS          NUMBER(15),
    STLM_SCDR_CPAY_PATH_GBCD    VARCHAR2(3),
    STLM_SCDR_VAN_GBCD          VARCHAR2(2),
    STLM_SCDR_REPY_POSS_AMT     NUMBER,
    STLM_SCDR_HDCRD_CLCC_YN     VARCHAR2(1),
    STLM_THRD_PAY_WAY_GBCD      VARCHAR2(2),
    STLM_THRD_PAY_WAY_GB_NM     VARCHAR2(100),
    STLM_THRD_FNC_ISTN_CD       VARCHAR2(3),
    STLM_THRD_CRDC_NM           VARCHAR2(100),
    STLM_THRD_INSM_MTHS         NUMBER,
    STLM_THRD_WINT_YN           VARCHAR2(1),
    STLM_THRD_WINT_CMIS         NUMBER(15),
    STLM_THRD_PAY_WAY_ADT_RATE  NUMBER,
    STLM_THRD_CRDC_CMIS_RATE    NUMBER,
    STLM_THRD_INSM_CMIS_RATE    NUMBER,
    STLM_THRD_CRDC_CMIS         NUMBER(15),
    STLM_THRD_INSM_CMIS         NUMBER(15),
    STLM_THRD_STLM_WAY_C_AMT    NUMBER,
    STLM_THRD_SUM_CMIS          NUMBER(15),
    STLM_THRD_CPAY_PATH_GBCD    VARCHAR2(3),
    STLM_THRD_VAN_GBCD          VARCHAR2(2),
    STLM_THRD_REPY_POSS_AMT     NUMBER,
    STLM_THRD_HDCRD_CLCC_YN     VARCHAR2(1),
    VEN_CNCS_RGST_ID            VARCHAR2(50),
    RNTL_MD_CNFM_DT             DATE,
    RNTL_MD_CNFR_ID             VARCHAR2(50),
    RNTL_HNDLV_AMT              NUMBER,
    RNTL_CNCS_QTY               NUMBER,
    INTG_ITEM_ARLT_AMT          NUMBER,
    ARS_DC_AMT_VAT              NUMBER(10),
    SPYM_DC_AMT_VAT             NUMBER(10),
    COPN_DC_AMT_VAT             NUMBER(10),
    EMP_DC_AMT_VAT              NUMBER,
    ETC_DC_AMT_VAT              NUMBER(10),
    B2E_DC_AMT_VAT              NUMBER(10),
    CRD_PRMO_DC_AMT_VAT         NUMBER,
    SVMT_PRDC_AMT_VAT           NUMBER(10),
    TCOMM_DC_AMT_VAT            NUMBER,
    SPDC_AMT_VAT                NUMBER,
    PRMO_DC_AMT_VAT             NUMBER(10),
    SOON_USE_COPN_DC_AMT_VAT    NUMBER(10),
    MASS_BUY_DC_AMT_VAT         NUMBER,
    FRGN_DLVC_AMT_VAT           NUMBER,
    RTP_DSRV_COST_VAT           NUMBER,
    IRGN_MNTR_DLVC_AMT_VAT      NUMBER,
    GIFT_DC_AMT_VAT             NUMBER,
    AFCR_DC_AMT_VAT             NUMBER,
    NCHG_DLV_COPN_DC_AMT_VAT    NUMBER,
    ADD_DLVC_AMT_VAT            NUMBER,
    EXCH_DSRV_COST_VAT          NUMBER,
    MXPK_GIFT_AMT_VAT           NUMBER,
    ARS_DC_APLY_RATE            NUMBER,
    SPYM_DC_APLY_RATE           NUMBER,
    COPN_DC_APLY_RATE           NUMBER,
    EMP_DC_RATE                 NUMBER,
    ETC_DC_RATE                 NUMBER(22,3),
    B2E_DC_APLY_RATE            NUMBER,
    CRD_PRMO_DC_RATE            NUMBER(22,3),
    SVMT_PRDC_RATE              NUMBER,
    TCOMM_DC_RATE               NUMBER(22,3),
    SPDC_RATE                   NUMBER,
    PRMO_DC_RATE                NUMBER(22,2),
    SOON_USE_COPN_DC_RATE       NUMBER,
    MASS_BUY_DC_RATE            NUMBER(22,3),
    DLVC_RATE                   NUMBER(22,3),
    FRGN_DLVC_RATE              NUMBER(22,3),
    RTP_DSRV_COST_RATE          NUMBER(22,3),
    IRGN_MNTR_DLVC_RATE         NUMBER(22,3),
    GIFT_DC_RATE                NUMBER(22,3),
    AFCR_DC_RATE                NUMBER,
    NCHG_DLV_COPN_DC_RATE       NUMBER(22,3),
    ADD_DLVC_RATE               NUMBER(22,3),
    EXCH_DSRV_COST_RATE         NUMBER(22,3),
    MXPK_GIFT_RATE              NUMBER(22,3),
    STLM_WAY_DC_RATE            NUMBER(22,3),
    STLM_AMT_DC_COPN_RATE       NUMBER,
    CRD_IMDC_RATE               NUMBER,
    DVLB_POSS_DC_AMT            NUMBER(10),
    SALE_PRFT_CRD_IMDC_INCL     NUMBER,
    ARS_DC_AMT                  NUMBER(10),
    SPYM_DC_AMT                 NUMBER(10),
    COPN_DC_AMT                 NUMBER(10),
    EMP_DC_AMT                  NUMBER(10),
    ETC_DC_AMT                  NUMBER(10),
    B2E_DC_AMT                  NUMBER(10),
    CRD_PRMO_DC_AMT             NUMBER(10),
    SVMT_PRDC_AMT               NUMBER(10),
    TCOMM_DC_AMT                NUMBER(10),
    SPDC_AMT                    NUMBER(10),
    PRMO_DC_AMT                 NUMBER(10),
    SOON_USE_COPN_DC_AMT        NUMBER(10),
    MASS_BUY_DC_AMT             NUMBER(10),
    DLV_DC_COST                 NUMBER,
    FRGN_DLVC_AMT               NUMBER,
    RTP_DSRV_COST               NUMBER,
    IRGN_MNTR_DLVC_AMT          NUMBER,
    GIFT_DC_AMT                 NUMBER(10),
    AFCR_DC_AMT                 NUMBER(10),
    NCHG_DLV_COPN_DC_AMT        NUMBER(10),
    ADD_DLVC_AMT                NUMBER,
    EXCH_DSRV_COST              NUMBER,
    MXPK_GIFT_AMT               NUMBER,
    VEN_DVLB_AMT                NUMBER,
    STLM_WAY_DC_AMT             NUMBER,
    STLM_AMT_DC_COPN_AMT        NUMBER,
    CRD_IMDC_AMT                NUMBER,
    REAL_SALE_AMT               NUMBER,
    RORD_AMT                    NUMBER,
    ORD_AMT                     NUMBER,
    CNCL_AMT                    NUMBER,
    RTP_AMT                     NUMBER,
    RTP_CNCL_AMT                NUMBER,
    EXCH_AMT                    NUMBER,
    SALE_PRFT_AMT               NUMBER,
    VACO_AMT                    NUMBER,
    CTPF_AMT                    NUMBER,
    FRPHSE_COST                 NUMBER,
    CRD_FRCS_CMIS               NUMBER(15),
    WINT_INSM_CMIS              NUMBER(15),
    CMS_CMIS                    NUMBER(15),
    GC_CMIS                     NUMBER(15),
    AFCR_SELL_CMIS              NUMBER(15),
    DLV_COST                    NUMBER,
    PACK_COST                   NUMBER,
    CALL_LACO                   NUMBER,
    PHDS_LACO                   NUMBER,
    MD_GRNT_HPNT                NUMBER,
    PRMP_OWCO_DVLB_COST         NUMBER,
    BRCM                        NUMBER(15),
    JWL_JGMT_COST               NUMBER,
    CRD_DMND_DC_AMT             NUMBER(10),
    SPYM_DC_VEN_DVLB_AMT        NUMBER,
    SMS_SEND_COST               NUMBER,
    ARS_DC_VEN_CHRG_AMT         NUMBER,
    PER_CO_SVMT                 NUMBER,
    PGM_FRCS_CMIS               NUMBER(15),
    PGM_WINT_INSM_CMIS          NUMBER(15),
    PGM_GIFT_COST               NUMBER,
    BROD_MD_GRNT_HPNT           NUMBER,
    BROD_RWD_HPNT               NUMBER,
    INTG_ITEM_SALE_PRFT_AMT     NUMBER,
    INTG_ITEM_SALE_PRFT_QTY     NUMBER,
    INTG_ITEM_SALE_PRFT_DC_AMT  NUMBER,
    DPRCH_LOSS_AMT              NUMBER,
    BASE_ACM_HPNT               NUMBER,
    RNTL_FXRT_CMIS              NUMBER(15),
    KAKAO_ORD_CMIS              NUMBER(15),
    PGM_CMPS_ITEM_GIFT_GBCD     VARCHAR2(1),
    PGM_PRMO_GIFT_OFFR_QTY      NUMBER,
    PGM_CMS_STLM_CNT            NUMBER,
    ITEM_EVAL_GIFT_COST         NUMBER,
    ITEM_EVAL_GIFT_DLV_COST     NUMBER,
    ITEM_EVAL_GIFT_PHDS_LACO    NUMBER,
    AFF_VACO_AMT                NUMBER,
    SPDC_DVLB_AMT               NUMBER,
    SOON_USE_COPN_VEN_DVLB_AMT  NUMBER,
    RWD_HPNT                    NUMBER,
    IMDC_CRDC_DVLB_AMT          NUMBER,
    WINT_INSM_CMIS_VEN_DVLB_AMT NUMBER,
    GIFT_COST                   NUMBER,
    GIFT_PRMP_COST              NUMBER,
    VACO_SMRY_AMT               NUMBER,
    CMIS_EXCLD_VACO_AMT         NUMBER,
    CRD_IMDC_INCL_VACO_AMT      NUMBER,
    CRD_DC_AMT                  NUMBER(10),
    CRD_IMDC_OWCO_DVLB_AMT      NUMBER,
    TOT_RWD_AMT                 NUMBER,
    TOT_DC_VEN_DVLB_AMT         NUMBER,
    ALML_ORD_NO                 VARCHAR2(30),
    ALML_CD                     VARCHAR2(2),
    ALML_NM                     VARCHAR2(100),
    ALML_ITEM_CD                VARCHAR2(30),
    ALML_ITEM_NM                VARCHAR2(100),
    ALML_TOT_DC_AMT             NUMBER(10),
    ALML_DC_AMT                 NUMBER(10),
    ALML_ORD_DTM                DATE,
    ALML_SELL_GBCD              VARCHAR2(2),
    ALML_SELL_GB_NM             VARCHAR2(100),
    WDAY_NM                     VARCHAR2(50),
    HLDY_YN                     VARCHAR2(1),
    MM_BSIC_WKNO                NUMBER,
    MM_BSIC_WKNO_NM             VARCHAR2(50),
    Y2001_BSIC_WKNO             NUMBER,
    REMP_EMNO                   VARCHAR2(10),
    REMP_NM                     VARCHAR2(100),
    DSTN_TYPE_GBCD              VARCHAR2(2),
    DSTN_TYPE_GB_NM             VARCHAR2(50),
    ITEM_L_CSF_NM               VARCHAR2(100),
    ITEM_M_CSF_NM               VARCHAR2(100),
    ITEM_S_CSF_NM               VARCHAR2(100),
    ITEM_D_CSF_NM               VARCHAR2(100),
    ITEM_L_CSF_CD               VARCHAR2(8),
    ITEM_M_CSF_CD               VARCHAR2(8),
    ITEM_S_CSF_CD               VARCHAR2(8),
    ITEM_D_CSF_CD               VARCHAR2(8),
    RGST_ID                     VARCHAR2(50) NOT NULL,
    ETL_DTM                     DATE NOT NULL
)
TABLESPACE TS_DW_PB_01_DAT
STORAGE
(
    INITIAL 64K
    NEXT 1M
)
NOCOMPRESS;

CREATE INDEX DW_PB.POD_ORD_ANAL_DLU_FCT_01_IX_02
ON DW_PB.POD_ORD_ANAL_DLU_FCT_01 (ACPT_DT) 
TABLESPACE TS_DW_PB_01_DAT
STORAGE
(
    INITIAL 64K
    NEXT 1M
);

CREATE UNIQUE INDEX DW_PB.POD_ORD_ANAL_DLU_FCT_01_PK
ON DW_PB.POD_ORD_ANAL_DLU_FCT_01 (BSIC_DT,ORD_NO,ORD_PTC_SEQ) 
TABLESPACE TS_DW_PB_01_DAT
STORAGE
(
    INITIAL 64K
    NEXT 1M
);

CREATE INDEX DW_PB.POD_ORD_ANAL_DLU_FCT_01_IX_03
ON DW_PB.POD_ORD_ANAL_DLU_FCT_01 (ORD_DT) 
TABLESPACE TS_DW_PB_01_DAT
STORAGE
(
    INITIAL 64K
    NEXT 1M
);

ALTER TABLE DW_PB.POD_ORD_ANAL_DLU_FCT_01
ADD CONSTRAINT PK_POD_ORD_ANAL_DLU_FCT_01 PRIMARY KEY (BSIC_DT,ORD_NO,ORD_PTC_SEQ);

GRANT SELECT ON DW_PB.POD_ORD_ANAL_DLU_FCT_01 TO DW_IMSI;

COMMENT ON TABLE DW_PB.POD_ORD_ANAL_DLU_FCT_01 IS '주문분석일단위팩트';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.BSIC_DT IS '기준일자';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ORD_NO IS '주문번호';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ORD_PTC_SEQ IS '주문상세순번';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ORD_DT IS '주문일자';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ORD_DTM IS '주문일시';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ORD_SRC_GBCD IS '주문출처구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ACPT_DT IS '접수일자';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ACPT_DTM IS '접수일시';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CNCL_DT IS '취소일자';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.RTP_ACPT_DT IS '반품접수일자';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.RTP_CMPT_DT IS '반품완료일자';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.REPY_DT IS '환불일자';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.DSTF_CNSL_DT IS '불만상담일자';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.OSHP_DT IS '출고일자';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CUST_NO IS '고객번호';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.DSTN_SEQ IS '배송지순번';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SELL_MDA_GBCD IS '판매매체구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SELL_MDA_GB_NM IS '판매매체구분명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SELL_MDA_NO IS '판매매체번호';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SELL_MDA_NM IS '판매매체명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SELL_MDA_L_CSF_CD IS '판매매체대분류코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SELL_MDA_L_CSF_NM IS '판매매체대분류명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SELL_MDA_M_CSF_CD IS '판매매체중분류코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SELL_MDA_M_CSF_NM IS '판매매체중분류명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SELL_MDA_S_CSF_CD IS '판매매체소분류코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SELL_MDA_S_CSF_NM IS '판매매체소분류명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SELL_MDA_L_CSF_CD_BIZ_STRG IS '판매매체대분류코드_영전';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SLITM_CD IS '판매상품코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SLITM_NM IS '판매상품명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ITEM_GBCD IS '상품타입코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.BRND_CD IS '브랜드코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.BRND_NM IS '브랜드명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PRCH_MTHD_GBCD IS '매입방법구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PRCH_MTHD_GB_NM IS '매입방법구분명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.FAMT_FXRT_GBCD IS '정액정률구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.FAMT_FXRT_GB_NM IS '정액정률구분명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PRM_ITEM_CSF IS '상품분류1차';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SCDR_ITEM_CSF IS '상품분류2차';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.INTG_ITEM_STLM_YN IS '무형상품결제여부';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SET_ITEM_YN IS '세트상품여부';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SET_ORD_PTC_SEQ IS '세트주문상세순번';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SET_SLITM_CD IS '세트판매상품코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.UITM_CD IS '상품속성코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ITEM_PRC_APLY_DT IS '상품가격적용일자';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.MD_CD IS 'MD코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.MD_NM IS 'MD명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.DVSN_CD IS '사업부코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.DVSN_NM IS '사업부명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.TEAM_CD IS '팀코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.TEAM_NM IS '팀명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PART_CD IS '파트코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PART_NM IS '파트명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SRCN_MD_CD IS '소싱MD코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SRCN_MD_NM IS '소싱MD명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.BROD_MD_CD IS '방송MD코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.HMALL_MD_CD IS 'HMALLMD코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SECT_ID IS '매장ID';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.INFW_CH_CD IS '유입채널코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.INFW_CH_NM IS '유입채널명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.INFW_CH_L_CSF_NM IS '유입채널대분류명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.INFW_CH_M_CSF_NM IS '유입채널중분류명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.TC_CD IS 'TC코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.VEN_CD IS '협력사코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.VEN_NM IS '협력사명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.MDA_CROS_ARLT_ANAL_GBCD IS '매체교차실적분석구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.MDA_CROS_ARLT_ANAL_GB_NM IS '매체교차실적분석구분명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ALSW_NO IS '제휴검색어번호';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.BFMT_NO IS '방송편성번호';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PGM_CD IS 'PGM코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PGM_NM IS 'PGM명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.WEB_INF_EXPS_GBCD IS '웹정보노출구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.WEB_INF_EXPS_GB_NM IS '웹정보노출구분명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ORD_TYPE_GBCD IS '주문유형구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.DSTF_CNSL_CSF_CD IS '불만상담분류코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.LAST_ORD_STAT_GBCD IS '최종주문상태구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.LAST_ORD_STAT_GB_NM IS '최종주문상태구분명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CNCL_CNSL_CSF_CD IS '취소상담분류코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ORD_ITEM_GBCD IS '주문상품구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.BEF_ACPT_ORD_PTC_SEQ IS '이전접수주문상세순번';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.FRST_ACPT_ORD_PTC_SEQ IS '최초접수주문상세순번';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CMPS_ORPD_ORD_PTC_SEQ IS '구성본품주문상세순번';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.EXCH_BNDL_ORD_PTC_SEQ IS '교환묶음주문상세순번';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ACPT_CH_GBCD IS '접수채널구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ACPT_CH_GB_NM IS '접수채널구분명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.FRST_REG_PRCH_MDA_GBCD IS '최초등록매입매체구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.FRST_REG_PRCH_MDA_GB_NM IS '최초등록매입매체구분명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ITEM_MDA_GBCD IS '상품매체구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ITEM_MDA_GB_NM IS '상품매체구분명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.BROD_MDA_GBCD IS '방송매체구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.BROD_MDA_GB_NM IS '방송매체구분명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.MNG_WH_NO IS '관리창고번호';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.DLV_MAGN_GBCD IS '배송주체구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.DLVCO_CD IS '배송사코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.LRPY_YN IS '후환불여부';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.GIFT_PRMO_NO IS '사은품프로모션번호';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SELL_UPRC IS '판매단가';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ORD_QTY IS '주문수량';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CNCL_QTY IS '취소수량';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.RTP_QTY IS '반품수량';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.RTP_CNCL_QTY IS '반품취소수량';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.EXCH_QTY IS '교환수량';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ORD_ETC_QTY IS '주문기타수량';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ACPT_QTY IS '접수수량';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.RMND_QTY IS '잔여수량';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.RORD_QTY IS '순주문수량';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.GIFT_ORD_QTY IS '사은품주문수량';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.GIFT_RORD_QTY IS '사은품순주문수량';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.GIFT_CNCL_QTY IS '사은품취소수량';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.GIFT_RTP_QTY IS '사은품반품수량';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.GIFT_RTP_CNCL_QTY IS '사은품반품취소수량';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.DC_RATE IS '할인비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.VAT_RATE IS '부가세비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.TAXN_JDGM_YN IS '과세심사여부';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ORD_ETC_AMT IS '주문기타금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.EXP_CTPF_AMT IS '예상공헌이익금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PRFT_AMT IS '이익금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.DC_AMT IS '할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.MRGN_AMT IS '마진금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.TRD_AMT IS '거래금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.GMV_AMT IS 'GMV금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ORD_AMT_VAT IS '주문금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CNCL_AMT_VAT IS '취소금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.RTP_AMT_VAT IS '반품금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.RTP_CNCL_AMT_VAT IS '반품취소금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PRCH_PRC IS '매입가격';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PRCH_VAT IS '매입부가세';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SELL_PRC IS '판매가격';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SELL_VAT IS '판매부가세';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.MRGN_RATE IS '마진비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.EXP_SWRT_APLY_DT IS '예상전환율적용일자';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.EXP_SWRT IS '예상전환율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.REAL_SWRT IS '실전환율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.EXP_CTPF_RATE IS '예상공헌이익비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.DLV_FORM_GBCD IS '배송형태구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.VEN_CHRG_AMT IS '협력사부담금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ONLN_EXCL_ITEM_SWTC_YN IS '온라인전용상품전환여부';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SELL_PNTM_GBCD IS '판매시점구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.LBRD_L_CSF_NM IS '생방송대분류명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.LBRD_M_CSF_NM IS '생방송중분류명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.FXTM_DLV_YN IS '정기배송여부';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.FXTM_DLV_REQ_NO IS '정기배송신청번호';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_PRM_PAY_WAY_GBCD IS '결제1차지불수단구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_PRM_PAY_WAY_GB_NM IS '결제1차지불수단구분명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_PRM_FNC_ISTN_CD IS '결제1차금융기관코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_PRM_CRDC_NM IS '결제1차카드사명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_PRM_INSM_MTHS IS '결제1차할부개월수';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_PRM_WINT_YN IS '결제1차무이자여부';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_PRM_WINT_CMIS IS '결제1차무이자수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_PRM_PAY_WAY_ADT_RATE IS '결제1차지불수단가중비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_PRM_CRDC_CMIS_RATE IS '결제1차카드사수수료비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_PRM_INSM_CMIS_RATE IS '결제1차할부수수료비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_PRM_CRDC_CMIS IS '결제1차카드사수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_PRM_INSM_CMIS IS '결제1차할부수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_PRM_STLM_WAY_C_AMT IS '결제1차결제수단별금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_PRM_SUM_CMIS IS '결제1차합계수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_PRM_CPAY_PATH_GBCD IS '결제1차현금결제경로구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_PRM_VAN_GBCD IS '결제1차VAN구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_PRM_REPY_POSS_AMT IS '결제1차환불가능금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_PRM_HDCRD_CLCC_YN IS '결제1차현대카드CLCC여부';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_STAT_GBCD IS '결제상태구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_STAT_GB_NM IS '결제상태구분명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.WINT_CMIS IS '무이자수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CRDC_CMIS IS '카드사수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.INSM_CMIS IS '할부수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SUM_CMIS IS '합계수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.REPY_POSS_AMT IS '환불가능금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_AMT IS '결제금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CMPX_STLM_YN IS '복합결제여부';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_SCDR_PAY_WAY_GBCD IS '결제2차지불수단구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_SCDR_PAY_WAY_GB_NM IS '결제2차지불수단구분명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_SCDR_FNC_ISTN_CD IS '결제2차금융기관코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_SCDR_CRDC_NM IS '결제2차카드사명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_SCDR_INSM_MTHS IS '결제2차할부개월수';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_SCDR_WINT_YN IS '결제2차무이자여부';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_SCDR_WINT_CMIS IS '결제2차무이자수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_SCDR_PAY_WAY_ADT_RATE IS '결제2차지불수단가중비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_SCDR_CRDC_CMIS_RATE IS '결제2차카드사수수료비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_SCDR_INSM_CMIS_RATE IS '결제2차할부수수료비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_SCDR_CRDC_CMIS IS '결제2차카드사수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_SCDR_INSM_CMIS IS '결제2차할부수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_SCDR_STLM_WAY_C_AMT IS '결제2차결제수단별금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_SCDR_SUM_CMIS IS '결제2차합계수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_SCDR_CPAY_PATH_GBCD IS '결제2차현금결제경로구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_SCDR_VAN_GBCD IS '결제2차VAN구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_SCDR_REPY_POSS_AMT IS '결제2차환불가능금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_SCDR_HDCRD_CLCC_YN IS '결제2차현대카드CLCC여부';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_THRD_PAY_WAY_GBCD IS '결제3차지불수단구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_THRD_PAY_WAY_GB_NM IS '결제3차지불수단구분명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_THRD_FNC_ISTN_CD IS '결제3차금융기관코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_THRD_CRDC_NM IS '결제3차카드사명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_THRD_INSM_MTHS IS '결제3차할부개월수';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_THRD_WINT_YN IS '결제3차무이자여부';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_THRD_WINT_CMIS IS '결제3차무이자수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_THRD_PAY_WAY_ADT_RATE IS '결제3차지불수단가중비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_THRD_CRDC_CMIS_RATE IS '결제3차카드사수수료비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_THRD_INSM_CMIS_RATE IS '결제3차할부수수료비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_THRD_CRDC_CMIS IS '결제3차카드사수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_THRD_INSM_CMIS IS '결제3차할부수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_THRD_STLM_WAY_C_AMT IS '결제3차결제수단별금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_THRD_SUM_CMIS IS '결제3차합계수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_THRD_CPAY_PATH_GBCD IS '결제3차현금결제경로구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_THRD_VAN_GBCD IS '결제3차VAN구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_THRD_REPY_POSS_AMT IS '결제3차환불가능금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_THRD_HDCRD_CLCC_YN IS '결제3차현대카드CLCC여부';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.VEN_CNCS_RGST_ID IS '협력사체결등록자ID';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.RNTL_MD_CNFM_DT IS '렌탈MD확정일자';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.RNTL_MD_CNFR_ID IS '렌탈MD확정자ID';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.RNTL_HNDLV_AMT IS '렌탈취급고금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.RNTL_CNCS_QTY IS '렌탈체결수량';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.INTG_ITEM_ARLT_AMT IS '무형상품실적금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ARS_DC_AMT_VAT IS 'ARS할인금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SPYM_DC_AMT_VAT IS '일시불할인금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.COPN_DC_AMT_VAT IS '쿠폰할인금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.EMP_DC_AMT_VAT IS '직원할인금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ETC_DC_AMT_VAT IS '기타할인금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.B2E_DC_AMT_VAT IS 'B2E할인금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CRD_PRMO_DC_AMT_VAT IS '카드프로모션할인금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SVMT_PRDC_AMT_VAT IS '적립금선할인금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.TCOMM_DC_AMT_VAT IS 'T커머스할인금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SPDC_AMT_VAT IS '깜짝할인금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PRMO_DC_AMT_VAT IS '프로모션할인금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SOON_USE_COPN_DC_AMT_VAT IS '바로사용쿠폰할인금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.MASS_BUY_DC_AMT_VAT IS '대량구매할인금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.FRGN_DLVC_AMT_VAT IS '해외배송비금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.RTP_DSRV_COST_VAT IS '반품택배비용_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.IRGN_MNTR_DLVC_AMT_VAT IS '도서산간배송비금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.GIFT_DC_AMT_VAT IS '사은품할인금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.AFCR_DC_AMT_VAT IS '제휴사할인금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.NCHG_DLV_COPN_DC_AMT_VAT IS '무료배송쿠폰할인금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ADD_DLVC_AMT_VAT IS '추가배송비금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.EXCH_DSRV_COST_VAT IS '교환택배비용_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.MXPK_GIFT_AMT_VAT IS '합포장사은품금액_VAT포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ARS_DC_APLY_RATE IS 'ARS할인적용비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SPYM_DC_APLY_RATE IS '일시불할인적용비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.COPN_DC_APLY_RATE IS '쿠폰할인적용비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.EMP_DC_RATE IS '직원할인비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ETC_DC_RATE IS '기타할인비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.B2E_DC_APLY_RATE IS 'B2E할인적용비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CRD_PRMO_DC_RATE IS '카드프로모션할인비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SVMT_PRDC_RATE IS '적립금선할인비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.TCOMM_DC_RATE IS 'T커머스할인비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SPDC_RATE IS '깜짝할인비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PRMO_DC_RATE IS '프로모션할인비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SOON_USE_COPN_DC_RATE IS '바로사용쿠폰할인비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.MASS_BUY_DC_RATE IS '대량구매할인비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.DLVC_RATE IS '배송비비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.FRGN_DLVC_RATE IS '해외배송비비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.RTP_DSRV_COST_RATE IS '반품택배비용비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.IRGN_MNTR_DLVC_RATE IS '도서산간배송비비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.GIFT_DC_RATE IS '사은품할인비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.AFCR_DC_RATE IS '제휴사할인비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.NCHG_DLV_COPN_DC_RATE IS '무료배송쿠폰할인비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ADD_DLVC_RATE IS '추가배송비비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.EXCH_DSRV_COST_RATE IS '교환택배비용비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.MXPK_GIFT_RATE IS '합포장사은품비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_WAY_DC_RATE IS '결제수단할인비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_AMT_DC_COPN_RATE IS '결제금액할인쿠폰비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CRD_IMDC_RATE IS '카드즉시할인비율';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.DVLB_POSS_DC_AMT IS '분담가능할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SALE_PRFT_CRD_IMDC_INCL IS '매출총이익_카드즉시할인포함';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ARS_DC_AMT IS 'ARS할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SPYM_DC_AMT IS '일시불할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.COPN_DC_AMT IS '쿠폰할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.EMP_DC_AMT IS '직원할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ETC_DC_AMT IS '기타할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.B2E_DC_AMT IS 'B2E할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CRD_PRMO_DC_AMT IS '카드프로모션할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SVMT_PRDC_AMT IS '적립금선할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.TCOMM_DC_AMT IS 'T커머스할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SPDC_AMT IS '깜짝할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PRMO_DC_AMT IS '프로모션할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SOON_USE_COPN_DC_AMT IS '바로사용쿠폰할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.MASS_BUY_DC_AMT IS '대량구매할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.DLV_DC_COST IS '배송할인비용';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.FRGN_DLVC_AMT IS '해외배송비금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.RTP_DSRV_COST IS '반품택배비용';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.IRGN_MNTR_DLVC_AMT IS '도서산간배송비금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.GIFT_DC_AMT IS '사은품할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.AFCR_DC_AMT IS '제휴사할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.NCHG_DLV_COPN_DC_AMT IS '무료배송쿠폰할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ADD_DLVC_AMT IS '추가배송비금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.EXCH_DSRV_COST IS '교환택배비용';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.MXPK_GIFT_AMT IS '합포장사은품금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.VEN_DVLB_AMT IS '협력사분담금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_WAY_DC_AMT IS '결제수단할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.STLM_AMT_DC_COPN_AMT IS '결제금액할인쿠폰금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CRD_IMDC_AMT IS '카드즉시할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.REAL_SALE_AMT IS '실매출금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.RORD_AMT IS '순주문금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ORD_AMT IS '주문금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CNCL_AMT IS '취소금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.RTP_AMT IS '반품금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.RTP_CNCL_AMT IS '반품취소금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.EXCH_AMT IS '교환금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SALE_PRFT_AMT IS '매출이익금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.VACO_AMT IS '변동비금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CTPF_AMT IS '공헌이익금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.FRPHSE_COST IS '수신자부담전화비용';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CRD_FRCS_CMIS IS '카드가맹점수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.WINT_INSM_CMIS IS '무이자할부수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CMS_CMIS IS 'CMS수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.GC_CMIS IS '상품권수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.AFCR_SELL_CMIS IS '제휴사판매수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.DLV_COST IS '배송비용';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PACK_COST IS '포장비용';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CALL_LACO IS '콜인건비';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PHDS_LACO IS '물류인건비';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.MD_GRNT_HPNT IS 'MD부여H포인트';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PRMP_OWCO_DVLB_COST IS '경품자사분담비용';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.BRCM IS '브랜드수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.JWL_JGMT_COST IS '보석감정비용';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CRD_DMND_DC_AMT IS '카드청구할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SPYM_DC_VEN_DVLB_AMT IS '일시불할인협력사분담금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SMS_SEND_COST IS 'SMS전송비용';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ARS_DC_VEN_CHRG_AMT IS 'ARS할인협력사부담금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PER_CO_SVMT IS '당사적립금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PGM_FRCS_CMIS IS 'PGM가맹점수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PGM_WINT_INSM_CMIS IS 'PGM무이자할부수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PGM_GIFT_COST IS 'PGM사은품비용';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.BROD_MD_GRNT_HPNT IS '방송MD부여H포인트';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.BROD_RWD_HPNT IS '방송리워드H포인트';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.INTG_ITEM_SALE_PRFT_AMT IS '무형상품매출이익금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.INTG_ITEM_SALE_PRFT_QTY IS '무형상품매출이익수량';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.INTG_ITEM_SALE_PRFT_DC_AMT IS '무형상품매출이익할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.DPRCH_LOSS_AMT IS '직매입손실금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.BASE_ACM_HPNT IS '기본적립H포인트';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.RNTL_FXRT_CMIS IS '렌탈정률수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.KAKAO_ORD_CMIS IS '카카오주문수수료';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PGM_CMPS_ITEM_GIFT_GBCD IS 'PGM구성상품사은품구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PGM_PRMO_GIFT_OFFR_QTY IS 'PGM프로모션사은품제공수량';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.PGM_CMS_STLM_CNT IS 'PGMCMS결제건수';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ITEM_EVAL_GIFT_COST IS '상품평가사은품비용';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ITEM_EVAL_GIFT_DLV_COST IS '상품평가사은품배송비용';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ITEM_EVAL_GIFT_PHDS_LACO IS '상품평가사은품물류인건비';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.AFF_VACO_AMT IS '사후변동비금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SPDC_DVLB_AMT IS '깜짝할인분담금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.SOON_USE_COPN_VEN_DVLB_AMT IS '바로사용쿠폰협력사분담금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.RWD_HPNT IS '리워드H포인트';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.IMDC_CRDC_DVLB_AMT IS '즉시할인카드사분담금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.WINT_INSM_CMIS_VEN_DVLB_AMT IS '무이자할부수수료협력사분담금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.GIFT_COST IS '사은품비용';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.GIFT_PRMP_COST IS '사은품경품비용';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.VACO_SMRY_AMT IS '변동비요약금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CMIS_EXCLD_VACO_AMT IS '수수료제외변동비금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CRD_IMDC_INCL_VACO_AMT IS '카드즉시할인포함변동비금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CRD_DC_AMT IS '카드할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.CRD_IMDC_OWCO_DVLB_AMT IS '카드즉시할인자사분담금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.TOT_RWD_AMT IS '전체리워드금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.TOT_DC_VEN_DVLB_AMT IS '전체할인협력사분담금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ALML_ORD_NO IS '제휴몰주문번호';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ALML_CD IS '제휴몰코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ALML_NM IS '제휴몰명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ALML_ITEM_CD IS '제휴몰상품코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ALML_ITEM_NM IS '제휴몰상품명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ALML_TOT_DC_AMT IS '제휴몰전체할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ALML_DC_AMT IS '제휴몰할인금액';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ALML_ORD_DTM IS '제휴몰주문일시';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ALML_SELL_GBCD IS '제휴몰판매구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ALML_SELL_GB_NM IS '제휴몰판매구분명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.WDAY_NM IS '요일명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.HLDY_YN IS '휴일여부';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.MM_BSIC_WKNO IS '월기준주차';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.MM_BSIC_WKNO_NM IS '월기준주차명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.Y2001_BSIC_WKNO IS '2001년기준주차';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.REMP_EMNO IS '추천인사번';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.REMP_NM IS '추천인명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.DSTN_TYPE_GBCD IS '배송지유형구분코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.DSTN_TYPE_GB_NM IS '배송지유형구분명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ITEM_L_CSF_NM IS '상품대분류명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ITEM_M_CSF_NM IS '상품중분류명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ITEM_S_CSF_NM IS '상품소분류명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ITEM_D_CSF_NM IS '상품세분류명';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ITEM_L_CSF_CD IS '상품대분류코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ITEM_M_CSF_CD IS '상품중분류코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ITEM_S_CSF_CD IS '상품소분류코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ITEM_D_CSF_CD IS '상품세분류코드';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.RGST_ID IS '등록자ID';
COMMENT ON COLUMN DW_PB.POD_ORD_ANAL_DLU_FCT_01.ETL_DTM IS 'ETL일시';